version: '3'
services:
  db:
    image: mongo:5.0.9
    ports:
      - "10501:27017"
  nacos:
    image: nacos/nacos-server:v2.1.0
    container_name: nacos-standalone
    environment:
    - PREFER_HOST_MODE=hostname
    - MODE=standalone
    ports:
    - "10401:8848"
    - "10402:9848"