server:
  port: 10800
project:
  version: "0.0.1"
spring:
  application:
    name: "orders"
  data:
    mongodb:
      database: "micropos"
      host: "localhost"
      port: 10500
  cloud:
    nacos.discovery.server-addr: "http://localhost:10400"

springdoc:
  swagger-ui:
    use-root-path: true