server:
  port: 10301
spring:
  application:
    name: "gateway"
  cloud:
    nacos.discovery.server-addr: "http://localhost:10401"
    gateway:
      discovery:
        locator:
          enabled: true