server:
  port: 10300
spring:
  application:
    name: "gateway"
  cloud:
    nacos.discovery.server-addr: "http://localhost:10400"
    gateway:
      discovery:
        locator:
          enabled: true