name: CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        architecture: 'x64'
    - name: Setup coxbuild
      run: |
        python -m pip install coxbuild
        coxbuild --version
    - name: Prepare services
      run: |
        docker-compose up -d
    - name: CI
      env:
        PYTHONUTF8: 1
      run: |
        coxbuild ci
    - name: Shutdown services
      run: |
        docker-compose down
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ci
        path: ./dist/ci